### ISSUE TITLE
Bug in the structq

### ISSUE THREAD

**Issue by Flaviog03** [ZioEren/ValLang#1]
import ("console");

	struct auto{
		var modello;
		var cilindrata;
		var on_off = false;
	}

	var mobile = auto;
	
	
	print("Inserisci il modello");
	mobile.modello = input();
	
	print("Inserisci la cilindrata");
	mobile.cilindrata = input_int();
	
	print("Accesa?");
	mobile.on_off = input();
	
	if(mobile.on_off == 'si'){
		mobile.on_off = true;
	}
	else{
		mobile.on_off = false;
	}
	
	print("Il modello dell'auto e': " + mobile.modello);
	print("La cilindrata dell'auto e': " + mobile.cilindrata);
	
	if(mobile.on_off == true){
		print("L'auto e' accesa");
	}
	else{
		print("L'auto e' spenta");
	}

**Comment by ZioEren** [comment]
Solved! ;)
